### ISSUE TITLE
failure to open fivem crash

### ISSUE THREAD

**Issue by ghost** [vsousa14/FiveM-Server-Launcher#2]
when you give fivem to enter the server it crashes

**Comment by yogeshxd** [comment]
Same issue still trying to resolve it.

**Comment by yogeshxd** [comment]
For anyone having the same issue.

This issue is caused by the fivem's latest update. They now prohibit opening there application from shell/cmd. 

There is a walkarround though. You can add a line of code to open it from browser.

Here's what i did - 
![image](https://user-images.githubusercontent.com/45172882/123598414-1e0b4c80-d812-11eb-8b83-2346558ca825.png)
